name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Roda por favor!!!!!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "senha"
          envkey_POSTGRES_DB: "mp_test"
          envkey_DATABASE_URL: "postgresql://postgres:senha@postgres_mp_db:5432/mp_test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_mp_app npm run test
      - name: Build
        run: npm i && npm run build
